title: My Slide Show
description: Obsidian notes as slides
baseurl: "/obslide-show"
url: "https://nurselovely.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - "DailyNotes/"
  - "jekyll-stuff/"
  - "*.md"        # This ignores ALL notes...
  - "!index.md"   # my homepage
  - "!slides.md"  # future slides
